services:
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
     - .env
    ports:
     - "5000:5000"
    volumes:
     - .:/decloon-portfolio
    depends_on:
     - mysql
    networks:
     - backend
    
  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
     - .env
    volumes:
     - mydatabase:/var/lib/mysql
    networks:
     - backend

volumes:
  mydatabase:

networks:
  backend:
    driver: bridge
